### ISSUE TITLE
How can we add Tag

### ISSUE THREAD

**Issue by SkyNite** [ZhouShengsheng/AndroidTagViewLayout#1]
@ZhouShengsheng  Thanks for sharing this, can you suggest how can i add the Tag on Image Touch. eg Instagram, Facebook

**Comment by ZhouShengsheng** [comment]
@SkyNite First, you should add a TagViewLayout layer which is transparent onto the ImageView. When you touch on an ImageView, you can retrieve the relative location of the touch point. Then you just need to instantiate a TagView with the retrieved position and your own direction, and add it to the TagViewLayout.

**Comment by SkyNite** [comment]
@ZhouShengsheng : Thanks yar, i made id :D as per your suggestion
